### PR TITLE
Implement SDL 0173 Read Generic Network Signal Data

### LINKED ISSUE #990: [SDL 0173] Read Generic Network Signal Data
Proposal: [Read Generic Network Signal Data](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0173-Read-Generic-Network-Signal-data.md)

> This proposal is to make vehicle data APIs (GetVehicleData/SubscribeVehicleData/UnsubscribeVehicleData/OnVehicleData) more flexible to allow additional new vehicle data items, while maintaining the security access via policies.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/502

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with revisions. The author is to add a statement explaining how old core implementations using this method can be updated to expose new standardized vehicle data items. Additionally, the author is to add the three revisions noted in [this comment.](https://github.com/smartdevicelink/sdl_evolution/issues/502#issuecomment-465326262)

>The proposal .md was updated on March 11, 2019 to include the agreed upon revisions.

### PR DESCRIPTION
**Pull request by mrapitis**
Fixes #990

This PR is **ready** for review.

## Risk

This PR makes **minor** API changes.

## Testing Plan

Added new unit tests and expanded existing ones

## Summary

Added RPC structs, enums as defined in the Read Generic Network Signal Data proposal.

## CLA

- [x] I have signed the CLA

### CODE REVIEW

**Comment by theresalech** [comment]
@mrapitis as the proposal to revise this feature (https://github.com/smartdevicelink/sdl_evolution/issues/806) has been accepted, please advise when this PR has been tested by Ford and is ready for Livio review.

**Comment by mrapitis** [comment]
@smartdevicelink/android PR is ready for review, thanks!

**Comment by BrettyWhite** [comment]
@mrapitis i see you are changing a few things after it was 'ready for review'. Are you done changing things? We were looking to merge this,

**Comment by mrapitis** [comment]
@BrettyWhite  Yes, PR is ready for review.

I had to make a few small updates this morning:
Develop has been merged in because of the merge conflicts with the feature branch.  I also updated some docs and noticed an enum was wrong (the enum mistake was pointed out in the iOS PR yesterday and was present here is well.).  Thanks again.

**Comment by BrettyWhite** [comment]
Ok thanks, i see that the unit tests are still failing. I will wait until those are passing and then consider it ready for review. Thanks @mrapitis

**Comment by mrapitis** [comment]
@BrettyWhite unit tests now passing.

**Pull request merged**
