### PR TITLE
[0257] New vehicle data HandsOffSteering

### LINKED ISSUE #1224: [SDL 0257] New vehicle data HandsOffSteering
Proposal: [New vehicle data HandsOffSteering](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0257-New-vehicle-data-HandsOffSteering.md)

> This proposal is to add new vehicle data `HandsOffSteering` to know whether or not a driver has his or her hands on the steering wheel.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/857

### PR DESCRIPTION
**Pull request by kostyaBoss**
Fixes #1224 

This PR is **[ready]** for review.

### Risk
This PR makes **[minor]** API changes.

### Testing Plan
Covered by existing and added unit tests

#### Unit Tests
New unit tests covering introduced structures were added

### Summary
Applied [0257 New vehicle data HandsOffSteering](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0257-New-vehicle-data-HandsOffSteering.md) changes

#### Enhancements
    - Implement code changes related to HandsOffSteering

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by kostyaBoss** [comment]
@mrapitis , @atiwari9 please review the changes

**Comment by santhanamk** [comment]
@kostyaBoss I reviewed your PR.  I suggest you make the below changes.

**Source code changes:**

_SubscribeVehicleData.java:_
 - public void setHandsOffSteering should take in a Boolean instead of a boolean

_UnsubscribeVehicleData.java:_
 - public void setHandsOffSteering should take in a Boolean instead of a boolean

_OnVehicleData.java:_
 - public void setHandsOffSteering should take in a Boolean instead of a boolean

**Unit Test changes:**

_OnVehicleDataTests.java:_
 - Unit tests need to be added in 

_VehicleDataHelper.java:_
 - new Hands Off Steering Vehicle Data needs to be added in

_GetVehicleDataResponseTests.java:_
 - Unit tests need to be added in

**Comment by kostyaBoss** [comment]
@santhanamk updated according to provided suggestions, please review

**Comment by santhanamk** [comment]
@kostyaBoss I reviewed your changes.  They look good.  I have a few more suggestions:

**Unit tests changes:**

_GetVehicleDataResponseTests.java:_
 - towards the bottom of `testRpcValues()`, `assertNull(Test.NULL, msg.getHandsOffSteering());` is needed

**Comment by kostyaBoss** [comment]
@santhanamk Thanks for your feedback, I've updated PR, please check it

**Comment by santhanamk** [comment]
@kostyaBoss I checked the code and it looks good. Thanks.

**Comment by kostyaBoss** [comment]
@joeygrover , @theresalech Hi! Please review changes in this PR

**Comment by theresalech** [comment]
@kostyaBoss, can you please confirm that Ford has reviewed and approved this PR? I do not see any completed reviews yet. Thanks!

**Comment by kostyaBoss** [comment]
@theresalech The @santhanamk has approved this PR

**Comment by santhanamk** [comment]
@theresalech this PR is ready for Livio review.

**Comment by bilal-alsharifi** [comment]
@kostyaBoss Thanks for implementing the proposed changes. I noticed that the formatting in multiple files has been modified to fix some already-existing formatting issues. We plan to do the formatting fixes for the whole repo in a separate PR when we implement this [proposal](https://github.com/smartdevicelink/sdl_evolution/pull/926). Could you please revert the formatting changes and keep actual code changes only? that will keep the Git history cleaner and make it easier to trace any potential issues in the future.

**Comment by kostyaBoss** [comment]
@bilal-alsharifi Hi! I've made rollback of formatting changes, plese review PR

**Comment by kostyaBoss** [comment]
@bilal-alsharifi I don't know the reason, but check was cancelled for this branch. If you have access, please, restart it

**Comment by bilal-alsharifi** [comment]
@kostyaBoss Thanks for making the changes. I restarted the checks and they pass now. But I still see formatting changes in most of the files. For example `GetVehicleData`. Can we remove all the formatting changes from all modified files in this PR?

**Comment by kostyaBoss** [comment]
@bilal-alsharifi Hi! I've made corresponding changes, please, check the PR. Let me know, if there anything else I should change

**Comment by bilal-alsharifi** [comment]
@kostyaBoss Thanks for updating the PR. I am looking at the PR and I still see formatting changes. One example is the `GetVehicleData` class. Please look at the changed files in the PR and see how the whole file seems to be changed (formatting changes, reordering methods...). The PR is supposed to only add the changes in the proposal and not modify what is already existing.

**Comment by kostyaBoss** [comment]
@bilal-alsharifi Hi! Those changes are produced by the generator, and this was one of the tasks - to apply changes provided by the proposal using the generator, but it seems that this produced a lot of whitespace changes. If you check this PR using options "Hide whitespace changes" you will see the clean diff where there were only documentation changes and `handsOffSteering` added on the bottom of the files

**Comment by joeljfischer** [comment]
Hi @kostyaboss, as you note, the requirement was to provide the changes _for this proposal_ with the generator. Therefore the white space changes are out of scope. Please revert them.

**Comment by vladmu** [comment]
Hi @joeljfischer, @bilal-alsharifi,

In order to help @kostyaBoss I've tried to resolve formatting issues you mention and noticed the following problem. Some files in the current `develop` branch have different line endings in the one file, eg. `GetVehicleData.java` has `LF` line endings in `License Comment`, `setOEMCustomVehicleData` and `getOEMCustomVehicleData` methods and `CRLF` line endings in other lines of source. It is hard to manage and keep each line endings as is because even if IDE and Git have disabled all auto converting features, both mine and Kostya IDEs (Idea based) support one type of line ends for the whole file. I believe the last changes that we have here are the maximum we could provide without extra effort to fight with each line of code separately. Could you confirm it is suitable for you?
@santhanamk @mrapitis

**Comment by bilal-alsharifi** [comment]
Thanks, @vladmu @kostyaBoss for making the changes. You are right about the different line endings for the headers. This issue happened in the past because we used a script to add copyrights headings to some files. We plan to fix the line endings issue in another separate PR. It is fine if the headers are marked as changes in this PR as long as other formatting changes are removed.
I will review this PR and let you know about other potential changes.

**Pull request merged**
